### ISSUE TITLE
Does not work with Gradle 2.5

### ISSUE THREAD

**Issue by tkruse** [tkruse/gradle-groovysh-plugin#9]
Runtime Error:
```
Error: Could not find or load main class org.codehaus.groovy.tools.shell.PatchedMain
```

Compile error:
```
/home/kruset/work/java/gradle-groovysh-plugin/src/main/groovy/com/tkruse/gradle/groovysh/PatchedMainCompileTask.java:35: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/kruset/work/java/gradle-groovysh-plugin/src/main/groovy/com/tkruse/gradle/groovysh/PatchedMainCompileTask.java:46: error: cannot find symbol
        super.executeWithoutThrowingTaskFailure();
             ^
  symbol: method executeWithoutThrowingTaskFailure()
```

**Comment by tkruse** [comment]
fixed with e6b0dd63d333a1
